apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: microservicios
  name: microservicios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicios
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: microservicios
    spec:
      containers:
      - image: tomasrm/calcular-nuevos-precios:latest
        name: calcular-nuevos-precios
        resources: {}
status: {}
