apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: microservicios
  name: microservicios
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: microservicios
  type: ClusterIP
status:
  loadBalancer: {}
